AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sedes-api-serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  SedesLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function for Sedes API with DynamoDB and S3 integration.
      CodeUri: ./src/ServerlessAPI/
      Handler: ServerlessAPI
      Runtime: dotnet8
      Environment:
        Variables:
          DYNAMODB_TABLE: Sedes
          S3_BUCKET: sedes-images-bucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SedesTable
        - S3CrudPolicy:
            BucketName: sedes-images-bucket
        - Statement:
            Effect: Allow
            Action:
              - ses:SendEmail
            Resource: "*"
      Events:
        SedesApiPost:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: /api/sedes
            Method: POST
        SedesApiGet:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: /api/sedes/{id}
            Method: GET

  SedesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Sedes
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
