    services:

      cursos:
        container_name: ms-cursos-container
        build: 
          context: ./cursos
          dockerfile: Dockerfile
        image: ms-cursos-docker
        networks:
          - microservices-network
        ports:
          - "9999:9999"
          - "5001:5001"
          
      usuarios:
        container_name: ms-usuarios-container
        build: 
          context: ./usuarios
          dockerfile: Dockerfile
        image: ms-usuarios-docker
        networks:
          - microservices-network
        ports:
          - "7777:7777"

      docentes:
        container_name: ms-docentes-container
        build: 
          context: ./docentes
          dockerfile: Dockerfile
        image: ms-docentes-docker
        networks:
          - microservices-network
        ports:
          - "8888:8888"    
      
      sonarqube:
        container_name: sonarqube
        image: sonarqube:lts-community
        restart: always
        depends_on:
          - sonarqube-db
        networks:
          - microservices-network
        ports:
          - "9000:9000"
        environment:
          SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
          SONAR_JDBC_USERNAME: sonar
          SONAR_JDBC_PASSWORD: sonar

      sonarqube-db:
        container_name: sonarqube-db
        image: postgres:14
        restart: always
        networks:
          - microservices-network
        environment:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar
          POSTGRES_DB: sonarqube
        volumes:
          - sonarqube_db_data:/var/lib/postgresql/data

    networks:
      microservices-network:
        name: microservices-network
        driver : bridge
        
    volumes:
      sonarqube_db_data:

